tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "bash-completion"
brew "mas"
brew "nodebrew"
brew "peco"
brew "pipenv"
brew "pyenv"
brew "tree"
cask "alfred"
cask "cyberduck"
cask "discord"
cask "dropbox"
cask "google-chrome"
cask "insomnia"
cask "iterm2"
cask "karabiner-elements"
cask "microsoft-excel"
cask "microsoft-powerpoint"
cask "microsoft-word"
cask "phpstorm"
cask "sequel-pro"
cask "stoplight-studio"
cask "vagrant"
cask "visual-studio-code"
cask "zoomus"
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Magnet", id: 441258766
