#!/bin/bash

if [ "$(uname)" == 'Darwin' ]; then
    OS='Mac'
    chmod +x ./bin/macos.sh
    ./bin/macos.sh
elif [ "$(expr substr $(uname -s) 1 5)" == 'Linux' ]; then
    OS='Linux'
    chmod +x ./bin/linux.sh
    ./bin/linux.sh
else
    echo "Your plat
    form ($(uname -a)) is not supported."
    exit 1
fi

echo "command install"

# 全体設定
# TODO: LTSをインストールできるようにする
pyenv install 3.8.2
pyenv global 3.8.2

# xonsh 環境構築
# 以下は pip が入っていることが前提
echo "xonsh..."
pip install xonsh Pygments xontrib-z xontrib-enhancd

# フォントインストール
# git clone --depth 1 https://github.com/ryanoasis/nerd-fonts.git
# cd nerd-fonts; ./install.sh RobotoMono && cd ../; rm -rf nerd-fonts

# シンボリックリンク
chmod +x ./bin/symboliclink.sh
./bin/symboliclink.sh

# git
git config --global user.email "taittide@gmail.com"
git config --global user.name "sun-yryr"
