# ~/.zshrc file for zsh interactive shells.

# dotfilesディレクトリのパスを設定
export DOTFILES_DIR="${DOTFILES_DIR:-$HOME/Documents/dotfiles}"

# ------------------------------------------------------------
# OSごとの設定の読み込み
# 特にhomebrewなど、先にパスを設定しておかないときと、基本設定の解決ができない場合が多い
# ------------------------------------------------------------
if [[ "$OSTYPE" == "darwin"* ]]; then
  # macOS
  source "$DOTFILES_DIR/shell/zsh/os/macos.zsh"
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
  # Linux
  if [ -f /etc/os-release ]; then
    . /etc/os-release
    if [[ "$ID" == "ubuntu" ]]; then
      # Ubuntu
      source "$DOTFILES_DIR/shell/zsh/os/ubuntu.zsh"
    fi
  fi
fi

# ------------------------------------------------------------
# 基本設定の読み込み
# ------------------------------------------------------------
for config_file in "$DOTFILES_DIR/shell/zsh/base"/*.zsh; do
  source "$config_file"
done

# ------------------------------------------------------------
# ホスト名ベースの設定の読み込み
# ------------------------------------------------------------
HOST_CONFIG="$DOTFILES_DIR/shell/zsh/hosts/$(hostname).zsh"
if [ -f "$HOST_CONFIG" ]; then
  source "$HOST_CONFIG"
fi

# ------------------------------------------------------------
# ローカル設定の読み込み
# ------------------------------------------------------------
if [ -f "$HOME/.zshrc.local" ]; then
  source "$HOME/.zshrc.local"
fi

# ------------------------------------------------------------
# その他
# ------------------------------------------------------------
export GPG_TTY=$(tty)

# ------------------------------------------------------------
# mise
# ------------------------------------------------------------
eval "$($HOME/.local/bin/mise activate zsh)"

# ------------------------------------------------------------
# Starshipの起動（必ず最後に実行する）
# ------------------------------------------------------------
eval "$(starship init zsh)"
